In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
float_formatter = lambda x: "%.2f" % x
np.set_printoptions(formatter={'float_kind':float_formatter})

In [2]:
df = pd.read_csv("breast_cancer.csv")
df.shape

(569, 33)

In [3]:
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

      ...       texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0     ...               17.33           184.60      2019.0            0.1622   
1     ...               23.41           158.80      1956.0            0.1238   
2     ...               25.53           152.50      1709.0            0.1444   
3     ...               26.50            98.87       567.7            0.2098   
4     ...               16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [4]:
df.describe()

id  radius_mean  texture_mean  perimeter_mean    area_mean  \
count  5.690000e+02   569.000000    569.000000      569.000000   569.000000   
mean   3.037183e+07    14.127292     19.289649       91.969033   654.889104   
std    1.250206e+08     3.524049      4.301036       24.298981   351.914129   
min    8.670000e+03     6.981000      9.710000       43.790000   143.500000   
25%    8.692180e+05    11.700000     16.170000       75.170000   420.300000   
50%    9.060240e+05    13.370000     18.840000       86.240000   551.100000   
75%    8.813129e+06    15.780000     21.800000      104.100000   782.700000   
max    9.113205e+08    28.110000     39.280000      188.500000  2501.000000   

       smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       symmetry_mean     ...       texture_worst  perimeter_worst  \
count     569.000000     ...          569.000000       569.000000   
mean        0.181162     ...           25.677223       107.261213   
std         0.027414     ...            6.146258        33.602542   
min         0.106000     ...           12.020000        50.410000   
25%         0.161900     ...           21.080000        84.110000   
50%         0.179200     ...           25.410000        97.660000   
75%         0.195700     ...           29.720000       125.400000   
max         0.304000     ...           49.540000       251.200000   

        area_worst  smoothness_worst  compactness_worst  concavity_worst  \
count   569.000000        569.000000         569.000000       569.000000   
mean    880.583128          0.132369           0.254265         0.272188   
std     569.356993          0.022832           0.157336         0.208624   
min     185.200000          0.071170           0.027290         0.000000   
25%     515.300000          0.116600           0.147200         0.114500   
50%     686.500000          0.131300           0.211900         0.226700   
75%    1084.000000          0.146000           0.339100         0.382900   
max    4254.000000          0.222600           1.058000         1.252000   

       concave points_worst  symmetry_worst  fractal_dimension_worst  \
count            569.000000      569.000000               569.000000   
mean               0.114606        0.290076                 0.083946   
std                0.065732        0.061867                 0.018061   
min                0.000000        0.156500                 0.055040   
25%                0.064930        0.250400                 0.071460   
50%                0.099930        0.282200                 0.080040   
75%                0.161400        0.317900                 0.092080   
max                0.291000        0.663800                 0.207500   

       Unnamed: 32  
count          0.0  
mean           NaN  
std            NaN  
min            NaN  
25%            NaN  
50%            NaN  
75%            NaN  
max            NaN  

[8 rows x 32 columns]

In [5]:
df = df.iloc[:,:-1]

In [6]:
df.shape

(569, 32)

In [7]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')

In [8]:
x = df.iloc[:,2:].values
y = df.iloc[:,1].values

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y) # changing M and B as 1 and 0

In [10]:
print(x.shape)
print(y.shape)

(569, 30)
(569,)


In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)
print(x_train.shape, x_test.shape)
print(y_train.shape, y_test.shape)

(455, 30) (114, 30)
(455,) (114,)


In [13]:
x_train[:5]

array([[12.90, 15.92, 83.74, 512.20, 0.09, 0.10, 0.05, 0.03, 0.18, 0.06,
        0.21, 0.77, 1.69, 16.64, 0.01, 0.02, 0.02, 0.01, 0.02, 0.00,
        14.48, 21.82, 97.17, 643.80, 0.13, 0.25, 0.21, 0.10, 0.35, 0.08],
       [14.53, 13.98, 93.86, 644.20, 0.11, 0.09, 0.07, 0.06, 0.17, 0.06,
        0.31, 0.72, 2.14, 25.70, 0.01, 0.01, 0.02, 0.01, 0.02, 0.00,
        15.80, 16.93, 103.10, 749.90, 0.13, 0.15, 0.14, 0.11, 0.26, 0.08],
       [17.60, 23.33, 119.00, 980.50, 0.09, 0.20, 0.21, 0.10, 0.17, 0.07,
        0.93, 1.47, 5.80, 104.90, 0.01, 0.07, 0.07, 0.02, 0.02, 0.01,
        21.57, 28.87, 143.60, 1437.00, 0.12, 0.48, 0.52, 0.20, 0.23,
        0.12],
       [8.89, 14.64, 58.79, 244.00, 0.10, 0.15, 0.09, 0.03, 0.19, 0.09,
        0.53, 0.85, 3.17, 25.44, 0.02, 0.09, 0.06, 0.02, 0.03, 0.02,
        9.73, 15.67, 62.56, 284.40, 0.12, 0.24, 0.14, 0.05, 0.23, 0.11],
       [10.60, 18.95, 69.28, 346.40, 0.10, 0.11, 0.06, 0.03, 0.19, 0.06,
        0.45, 1.20, 3.43, 27.10, 0.01, 0.04, 0.03, 0

In [14]:
y_train

array([0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,

In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [16]:
print(len(y_train))
print(y_train.sum())

455
163


In [17]:
from sklearn.linear_model import LogisticRegression

In [18]:
# Building model
lr_model = LogisticRegression()
lr_model.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [19]:
lr_model.intercept_

array([-0.32])

In [20]:
lr_model.coef_

array([[-2.25, -0.05, 0.08, -0.00, 0.15, 0.43, 0.63, 0.33, 0.23, 0.04,
        0.00, -1.09, -0.53, 0.09, 0.03, 0.05, 0.10, 0.05, 0.07, 0.00,
        -1.18, 0.28, 0.14, 0.03, 0.28, 1.05, 1.34, 0.58, 0.69, 0.12]])

In [21]:
?accuracy_score()

In [22]:
accuracy_score(y_train, lr_model.predict(x_train))

0.967032967032967

In [23]:
?confusion_matrix()

In [24]:
confusion_matrix(y_train,lr_model.predict(x_train))

array([[286,   6],
       [  9, 154]], dtype=int64)

In [25]:
p_score = lr_model.predict_proba(x_train)[:,1]

In [26]:
lr_model.predict(x_train)

array([0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,

In [27]:
p_score

array([0.03, 0.01, 1.00, 0.00, 0.01, 0.01, 0.00, 0.83, 0.00, 0.01, 0.10,
       0.03, 1.00, 0.01, 1.00, 0.11, 0.00, 0.16, 0.02, 0.51, 0.00, 0.00,
       0.01, 1.00, 0.19, 0.00, 0.00, 0.04, 0.06, 1.00, 1.00, 0.57, 1.00,
       0.01, 0.02, 0.00, 1.00, 0.00, 0.04, 0.01, 0.11, 0.01, 1.00, 1.00,
       1.00, 0.01, 0.01, 0.01, 0.59, 0.00, 0.56, 0.64, 0.03, 1.00, 0.01,
       1.00, 0.00, 0.99, 0.68, 0.00, 1.00, 0.01, 1.00, 0.03, 1.00, 0.99,
       0.87, 0.02, 0.93, 0.00, 0.01, 0.00, 0.00, 1.00, 0.04, 1.00, 0.02,
       0.01, 0.34, 1.00, 0.44, 1.00, 0.00, 1.00, 1.00, 1.00, 1.00, 0.01,
       0.00, 1.00, 0.07, 0.00, 0.00, 0.62, 0.00, 1.00, 0.17, 0.00, 0.06,
       0.05, 0.05, 1.00, 0.01, 0.00, 0.13, 0.02, 0.02, 0.09, 1.00, 0.92,
       0.01, 0.99, 0.00, 0.00, 1.00, 0.00, 0.99, 1.00, 0.00, 0.01, 1.00,
       0.04, 0.00, 0.06, 0.00, 1.00, 1.00, 0.86, 0.01, 0.01, 0.00, 0.00,
       1.00, 0.01, 0.03, 0.76, 0.00, 1.00, 0.00, 0.00, 0.41, 0.01, 0.99,
       1.00, 1.00, 1.00, 0.00, 0.01, 0.01, 0.00, 1.

In [28]:
c_5 = p_score > 0.5

In [29]:
c_5

array([False, False,  True, False, False, False, False,  True, False,
       False, False, False,  True, False,  True, False, False, False,
       False,  True, False, False, False,  True, False, False, False,
       False, False,  True,  True,  True,  True, False, False, False,
        True, False, False, False, False, False,  True,  True,  True,
       False, False, False,  True, False,  True,  True, False,  True,
       False,  True, False,  True,  True, False,  True, False,  True,
       False,  True,  True,  True, False,  True, False, False, False,
       False,  True, False,  True, False, False, False,  True, False,
        True, False,  True,  True,  True,  True, False, False,  True,
       False, False, False,  True, False,  True, False, False, False,
       False, False,  True, False, False, False, False, False, False,
        True,  True, False,  True, False, False,  True, False,  True,
        True, False, False,  True, False, False, False, False,  True,
        True,  True,

In [30]:
c_5.astype(int)

array([0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,

In [31]:
confusion_matrix(y_train,c_5.astype(int))

array([[286,   6],
       [  9, 154]], dtype=int64)

In [32]:
c_7 = p_score >= 0.7
confusion_matrix(y_train,c_7.astype(int))

array([[291,   1],
       [ 17, 146]], dtype=int64)

In [33]:
c_3 = p_score >= 0.3
confusion_matrix(y_train,c_3.astype(int))

array([[280,  12],
       [  5, 158]], dtype=int64)

In [34]:
for t in np.arange(0,1,0.05):
    class_labels = p_score >= t
    print("Threshold is", t)
    print(confusion_matrix(y_train,class_labels.astype(int)))
    print()

Threshold is 0.0
[[  0 292]
 [  0 163]]

Threshold is 0.05
[[232  60]
 [  1 162]]

Threshold is 0.1
[[260  32]
 [  2 161]]

Threshold is 0.15000000000000002
[[271  21]
 [  2 161]]

Threshold is 0.2
[[278  14]
 [  4 159]]

Threshold is 0.25
[[279  13]
 [  4 159]]

Threshold is 0.30000000000000004
[[280  12]
 [  5 158]]

Threshold is 0.35000000000000003
[[281  11]
 [  7 156]]

Threshold is 0.4
[[282  10]
 [  7 156]]

Threshold is 0.45
[[283   9]
 [  9 154]]

Threshold is 0.5
[[286   6]
 [  9 154]]

Threshold is 0.55
[[287   5]
 [ 11 152]]

Threshold is 0.6000000000000001
[[288   4]
 [ 14 149]]

Threshold is 0.65
[[290   2]
 [ 15 148]]

Threshold is 0.7000000000000001
[[291   1]
 [ 17 146]]

Threshold is 0.75
[[291   1]
 [ 17 146]]

Threshold is 0.8
[[292   0]
 [ 19 144]]

Threshold is 0.8500000000000001
[[292   0]
 [ 22 141]]

Threshold is 0.9
[[292   0]
 [ 29 134]]

Threshold is 0.9500000000000001
[[292   0]
 [ 37 126]]



In [35]:
test_prob_scores = lr_model.predict(x_test)
test_prob_scores

array([0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0], dtype=int64)

In [36]:
test_prob_scores = lr_model.predict_proba(x_test)[:,1]
test_class_labels = test_prob_scores >= 0.3

In [37]:
print(confusion_matrix(y_test,test_class_labels.astype(int)))

[[63  2]
 [ 4 45]]


In [38]:
len(y_test)

114