In [ ]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns #Another library for visualization
np.set_printoptions(suppress=True)
sns.set_style("ticks") #to see seaborn inline in notebook
%matplotlib inline #to see matplotlib inline in notebook
plt.style.use("seaborn-poster")  # make bigger plots

In [2]:
df=pd.read_csv("housing_prices.csv")
df.head(10)

AREA  FLOOR  ROOM CODE  PRICE
0  1000      7     2    B   5618
1  1030      7     1    A   5201
2  1060      1     1    A   4779
3  1090      6     1    A   5425
4  1120      0     2    B   5657
5  1150      1     1    B   4945
6  1180      6     2    B   6475
7  1210      0     1    A   5352
8  1240      0     2    B   6290
9  1270      7     1    A   6147

In [3]:
df.shape

(50, 5)

In [4]:
df.dtypes

AREA      int64
FLOOR     int64
ROOM      int64
CODE     object
PRICE     int64
dtype: object

In [5]:
x=df.iloc[:,:-1]
x

AREA  FLOOR  ROOM CODE
0   1000      7     2    B
1   1030      7     1    A
2   1060      1     1    A
3   1090      6     1    A
4   1120      0     2    B
5   1150      1     1    B
6   1180      6     2    B
7   1210      0     1    A
8   1240      0     2    B
9   1270      7     1    A
10  1300     10     2    A
11  1330      3     2    B
12  1360      3     3    B
13  1390      8     3    B
14  1420      3     2    A
15  1450      7     2    B
16  1480      8     3    B
17  1510      7     2    A
18  1540      6     3    A
19  1570      8     3    A
20  1600      6     2    A
21  1630      4     3    B
22  1660      1     3    B
23  1690      3     3    B
24  1720      3     3    A
25  1750      0     2    A
26  1780      4     2    A
27  1810      1     3    B
28  1840      6     2    A
29  1870      6     3    A
30  1900      8     2    B
31  1930      8     2    B
32  1960      0     2    B
33  1990      8     2    A
34  2020      0     4    B
35  2050     10     3    A
36  2080      9     5    A
37  2110     10     3    A
38  2140      7     3    B
39  2170      1     4    B
40  2200      4     3    A
41  2230      3     3    B
42  2260      8     4    A
43  2290      4     4    B
44  2320      2     4    B
45  2350      5     4    B
46  2380     10     4    B
47  2410      6     4    B
48  2440      9     3    B
49  2470      3     3    B

In [6]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

code column to be converted to seperate column called A and B column
there are two types
oneHotEncoder
LabelEncoder

In [7]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder_x=LabelEncoder()

print(labelencoder_x.fit_transform(x[:,3]))
print(x[:,3])

[1 0 0 0 1 1 1 0 1 0 0 1 1 1 0 1 1 0 0 0 0 1 1 1 0 0 0 1 0 0 1 1 1 0 1 0 0
 0 1 1 0 1 0 1 1 1 1 1 1 1]
['B' 'A' 'A' 'A' 'B' 'B' 'B' 'A' 'B' 'A' 'A' 'B' 'B' 'B' 'A' 'B' 'B' 'A'
 'A' 'A' 'A' 'B' 'B' 'B' 'A' 'A' 'A' 'B' 'A' 'A' 'B' 'B' 'B' 'A' 'B' 'A'
 'A' 'A' 'B' 'B' 'A' 'B' 'A' 'B' 'B' 'B' 'B' 'B' 'B' 'B']


In [8]:
x[:,3]=labelencoder_x.fit_transform(x[:,3])

x[:10,]


array([[1000, 7, 2, 1],
       [1030, 7, 1, 0],
       [1060, 1, 1, 0],
       [1090, 6, 1, 0],
       [1120, 0, 2, 1],
       [1150, 1, 1, 1],
       [1180, 6, 2, 1],
       [1210, 0, 1, 0],
       [1240, 0, 2, 1],
       [1270, 7, 1, 0]], dtype=object)

In [9]:
onehotencoder=OneHotEncoder(categorical_features=[3])
onehotencoder.fit_transform(x)
x = onehotencoder.fit_transform(x).toarray()
x

array([[   0.,    1., 1000.,    7.,    2.],
       [   1.,    0., 1030.,    7.,    1.],
       [   1.,    0., 1060.,    1.,    1.],
       [   1.,    0., 1090.,    6.,    1.],
       [   0.,    1., 1120.,    0.,    2.],
       [   0.,    1., 1150.,    1.,    1.],
       [   0.,    1., 1180.,    6.,    2.],
       [   1.,    0., 1210.,    0.,    1.],
       [   0.,    1., 1240.,    0.,    2.],
       [   1.,    0., 1270.,    7.,    1.],
       [   1.,    0., 1300.,   10.,    2.],
       [   0.,    1., 1330.,    3.,    2.],
       [   0.,    1., 1360.,    3.,    3.],
       [   0.,    1., 1390.,    8.,    3.],
       [   1.,    0., 1420.,    3.,    2.],
       [   0.,    1., 1450.,    7.,    2.],
       [   0.,    1., 1480.,    8.,    3.],
       [   1.,    0., 1510.,    7.,    2.],
       [   1.,    0., 1540.,    6.,    3.],
       [   1.,    0., 1570.,    8.,    3.],
       [   1.,    0., 1600.,    6.,    2.],
       [   0.,    1., 1630.,    4.,    3.],
       [   0.,    1., 1660.,    

In [10]:
x=x[:,1:]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print("Train of x: ",x_train.shape) # x is always 2d so that (40,1)
print("Train of y:",y_train.shape) # y is always 1d so that (40,)
print("Test of x:",x_test.shape)
print('test of y:',y_test.shape)

Train of x:  (40, 4)
Train of y: (40,)
Test of x: (10, 4)
test of y: (10,)


In [11]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression() 
regressor.fit(x_train,y_train)
y_pred_test = regressor.predict(x_test)
print(y_pred_test)
y_pred_train = regressor.predict(x_train)
print(y_pred_train)

[10245.19877706 15153.05575446  9475.25705286 16173.06949372
  8615.32790548 14208.95859404  9344.89106848  8878.4230579
  8985.15761465 11577.68311488]
[ 9689.79105027  5885.30153403 13748.32717056  6328.13811698
  4324.46294724  6640.35812276 12900.35627663 16728.4772205
 16483.4275014   7725.6801506   5077.65753787 10577.32621427
 11686.53026252 14510.57030957  9585.96619859  6065.04296456
 15795.54119935 11172.5488039  10475.61395347  3432.95319426
 12506.89513983  6927.08470282 18852.67271206  4191.98437198
 10775.11307811  3769.05522045 15862.71148603 13526.90887909
 10907.59165337 13546.81631051  8107.18303396 10619.00307522
 11289.09453673 13786.02944252  8858.51562648  4233.66123293
 16775.99066854  7927.44160343  9744.18879237 12923.98770426]


In [12]:
#Metrics is used to evaluate the model , like r square,sse,mse,rmse
from sklearn.metrics import r2_score
model_score_train= r2_score(y_train, y_pred_train)
model_score_test= r2_score(y_test, y_pred_test)
print(model_score_train)
print(model_score_train.round(2))
print(model_score_test.round(2))


0.9461457392086273
0.95
0.95


In [13]:
print(y_pred_train.shape)
print(y_train.shape)

(40,)
(40,)


In [14]:
print(regressor.coef_)

[-668.22946341    3.69030486   88.93971621 2651.99720172]


In [15]:
x

array([[   1., 1000.,    7.,    2.],
       [   0., 1030.,    7.,    1.],
       [   0., 1060.,    1.,    1.],
       [   0., 1090.,    6.,    1.],
       [   1., 1120.,    0.,    2.],
       [   1., 1150.,    1.,    1.],
       [   1., 1180.,    6.,    2.],
       [   0., 1210.,    0.,    1.],
       [   1., 1240.,    0.,    2.],
       [   0., 1270.,    7.,    1.],
       [   0., 1300.,   10.,    2.],
       [   1., 1330.,    3.,    2.],
       [   1., 1360.,    3.,    3.],
       [   1., 1390.,    8.,    3.],
       [   0., 1420.,    3.,    2.],
       [   1., 1450.,    7.,    2.],
       [   1., 1480.,    8.,    3.],
       [   0., 1510.,    7.,    2.],
       [   0., 1540.,    6.,    3.],
       [   0., 1570.,    8.,    3.],
       [   0., 1600.,    6.,    2.],
       [   1., 1630.,    4.,    3.],
       [   1., 1660.,    1.,    3.],
       [   1., 1690.,    3.,    3.],
       [   0., 1720.,    3.,    3.],
       [   0., 1750.,    0.,    2.],
       [   0., 1780.,    4.,    2.],
 

In [16]:
regressor.predict([[1,20000,,4]])

array([26397.07594814])